version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rambani-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
    networks:
      - rambani-network

  mongo:
    image: mongo:4.4
    container_name: rambani-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo_data:/data/db
    networks:
      - rambani-network

  redis:
    image: redis:6-alpine
    container_name: rambani-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rambani-network

volumes:
  mongo_data:
  redis_data:

networks:
  rambani-network:
    driver: bridge
